### ISSUE TITLE
Is `babel-polyfill` necesary for production?

### ISSUE THREAD

**Issue by sirikon** [landakram/remark-parse-yaml#3]
It's included in `dependencies` inside `package.json` and also included int the npm release. Is it really necesary?

With it, the library should become a third of the current size when published.

**Comment by landakram** [comment]
It wasn't necessary - thanks for pointing this out!

I removed it in https://github.com/landakram/remark-parse-yaml/commit/97ca38f5bceb576e03f9ae33a8ad171ef92e4175 and cut a new `0.0.2` release, now published on npm.
